server:
  port: 8080

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/mr.ebignail
  cloud:
    gateway:
      server:
        routes:

          #            - id: identity-service
          #              uri: lb://IDENTITY-SERVICE
          #              predicates:
          #                - Path=/auth/**

          - id: security-service
            uri: lb://SECURITY-SERVICE
            predicates:
              - Path=/api/v1/security/**
          #              filters:
          #                - name: JwtAuthFilter

          - id: accounting-service
            uri: lb://ACCOUNTING-SERVICE
            predicates:
              - Path=/api/v1/accounting/**
          #              filters:
          #                - name: JwtAuthFilter

          - id: onboarding-service
            uri: lb://ONBOARDING-SERVICE
            predicates:
              - Path=/api/v1/onboarding/**
#              filters:
#                - name: JwtAuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    by.javaguru.jdmk10.gatewayservice.filter.JwtAuthFilter: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
