service:
  client:
    implementation: feign # или 'rest-template'

server:
  port: 8081

spring:
  application:
    name: onboarding-service
  datasource:
    url: jdbc:postgresql://localhost:5432/onboardingdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db.changelog/changelog.xml
    enabled: true
    drop-first: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

feign:
  okhttp:
    enabled: false
  httpclient:
    enabled: false
  hc5:
    enabled: true
  client:
    config:
      default:
        logger-level: basic
        connect-timeout: 5000
        read-timeout: 10000

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.net.ConnectException
          - java.io.IOException
          - feign.FeignException
    instances:
      accountingService:
        base-config: default
      profilerService:
        base-config: default
      securityService:
        base-config: default

  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.net.ConnectException
          - java.io.IOException
          - feign.FeignException
          - org.springframework.web.client.ResourceAccessException
    instances:
      accountingService:
        base-config: default
      profilerService:
        base-config: default
      securityService:
        base-config: default

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,retry

logging:
  level:
    by.javaguru.jdmk10.onboardingservice.client.feign: DEBUG



